# Docker Compose configuration file
services:
  # MongoDB Database Service
  mongodb:
    image: mongo:latest
    container_name: fiverr_mongodb
    ports:
      - "50000:27017" # Maps port 50000 on host to 27017 in container
    volumes:
      - mongo_data:/data/db # Persistence for database data
    networks:
      - fiverr_network

  # API (Backend) Service
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: fiverr_api
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - MONGO_URI=mongodb://mongodb:27017/fiverr # Using service name 'mongodb' as host
      - JWT_SECRET=${JWT_SECRET:-cA9x!zP7@YqRb6vLEj!KwT1nM2UdHG5Q!djfndskjfyau2167r}
      - JWT_EXPIRES=${JWT_EXPIRES:-1209600}
      - CLOUD_NAME=${CLOUD_NAME:-ddfkjjnxe}
      - CLOUD_API_KEY=${CLOUD_API_KEY:-563318394421961}
      - CLOUD_SECRET=${CLOUD_SECRET:-8zVF7OYoz58jcoJ4Oyf6J3i-c44}
      - CROSS_ORIGIN=http://localhost # Client service address
    depends_on:
      - mongodb
    networks:
      - fiverr_network

  # Client (Frontend) Service
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: fiverr_client
    ports:
      - "80:80" # Accessible via http://localhost
    environment:
      - VITE_API_URL=http://localhost:4000/api/
    depends_on:
      - api
    networks:
      - fiverr_network

# Networks definition
networks:
  fiverr_network:
    driver: bridge

# Volumes for persistent data
volumes:
  mongo_data:

